"""add_story_comments_table

Revision ID: b11a71e19547
Revises: ced16b418849
Create Date: 2025-03-27 11:13:54.946355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11a71e19547'
down_revision: Union[str, None] = 'ced16b418849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['story_comments.id'], name=op.f('fk_story_comments_parent_id_story_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_comments_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_comments'))
    )
    op.create_index('idx_story_comments_parent_id', 'story_comments', ['parent_id'], unique=False)
    op.create_index('idx_story_comments_posted_at', 'story_comments', ['posted_at'], unique=False)
    op.create_index('idx_story_comments_story_id', 'story_comments', ['story_id'], unique=False)
    op.create_index('idx_story_comments_user', 'story_comments', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_comments_user', table_name='story_comments')
    op.drop_index('idx_story_comments_story_id', table_name='story_comments')
    op.drop_index('idx_story_comments_posted_at', table_name='story_comments')
    op.drop_index('idx_story_comments_parent_id', table_name='story_comments')
    op.drop_table('story_comments')
    # ### end Alembic commands ###
