"""Item Entity

Revision ID: ced16b418849
Revises: fbc897ed9c61
Create Date: 2025-03-27 09:54:45.266654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced16b418849'
down_revision: Union[str, None] = 'fbc897ed9c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_entity_relations',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_value', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['item_entities.id'], name=op.f('fk_item_entity_relations_entity_id_item_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['processed_stories.id'], name=op.f('fk_item_entity_relations_item_id_processed_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'entity_id', name=op.f('pk_item_entity_relations'))
    )
    op.create_index('idx_item_entity_relation_scores', 'item_entity_relations', ['relation_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_item_entity_relation_scores', table_name='item_entity_relations')
    op.drop_table('item_entity_relations')
    # ### end Alembic commands ###
