"""Add item_entities table

Revision ID: fbc897ed9c61
Revises: 
Create Date: 2025-03-25 11:29:57.865860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc897ed9c61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_entities'))
    )
    op.create_index('idx_item_entities_name_type', 'item_entities', ['name', 'type'], unique=True)
    op.create_table('item_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_item_topics_name'))
    )
    op.create_table('processed_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('related_item_type', sa.String(), nullable=False),
    sa.Column('related_item_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_stories'))
    )
    op.create_index('idx_processed_stories_item', 'processed_stories', ['related_item_type', 'related_item_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index('idx_stories_posted_at', 'stories', ['posted_at'], unique=False)
    op.create_index('idx_stories_user', 'stories', ['user'], unique=False)
    op.create_table('item_topic_relations',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('relation_value', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['processed_stories.id'], name=op.f('fk_item_topic_relations_item_id_processed_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['item_topics.id'], name=op.f('fk_item_topic_relations_topic_id_item_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'topic_id', name=op.f('pk_item_topic_relations'))
    )
    op.create_index('idx_item_topic_relation_scores', 'item_topic_relations', ['relation_value'], unique=False)
    op.create_table('story_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('tstamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('vote_count >= 0', name=op.f('ck_story_votes_positive_vote_count')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_votes_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_votes'))
    )
    op.create_index('idx_story_votes_story_time', 'story_votes', ['story_id', 'tstamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_votes_story_time', table_name='story_votes')
    op.drop_table('story_votes')
    op.drop_index('idx_item_topic_relation_scores', table_name='item_topic_relations')
    op.drop_table('item_topic_relations')
    op.drop_index('idx_stories_user', table_name='stories')
    op.drop_index('idx_stories_posted_at', table_name='stories')
    op.drop_table('stories')
    op.drop_index('idx_processed_stories_item', table_name='processed_stories')
    op.drop_table('processed_stories')
    op.drop_table('item_topics')
    op.drop_index('idx_item_entities_name_type', table_name='item_entities')
    op.drop_table('item_entities')
    # ### end Alembic commands ###
